---
title: "Untitled"
author: "Yatong Li"
date: "February 8, 2015"
output: html_document
---

## Load the packages needed.

```{r}
suppressMessages(library(pander))
suppressMessages(library(GEOmetadb))
suppressMessages(library(data.table))
```

## Download the GEO database

```{r}
## This will download the entire database, so can be slow
if(!file.exists("GEOmetadb.sqlite"))
{
  # Download database only if it's not done already
  getSQLiteFile()
}
```

## Problem 1

```{r}
geo_con <- dbConnect(SQLite(), 'GEOmetadb.sqlite')
res <- dbGetQuery(geo_con, "SELECT 
            gse.title, 
            gse.gse, 
            gpl.gpl, 
            gpl.manufacturer, 
            gpl.title 
        FROM (gse JOIN gse_gpl ON gse.gse=gse_gpl.gse) j 
        JOIN gpl ON j.gpl=gpl.gpl 
        WHERE gse.title like '%HCV%'
            AND gpl.manufacturer like '%Illumina%' 
            AND gse.contact like '%Yale%';")
res
```

## Problem 2

```{r}
res.2 <- data.table(dbGetQuery(geo_con, "SELECT 
            gse.title, 
            gse.gse, 
            gpl.gpl, 
            gpl.manufacturer, 
            gpl.title 
        FROM (gse JOIN gse_gpl ON gse.gse=gse_gpl.gse) j 
        JOIN gpl ON j.gpl=gpl.gpl 
        WHERE gse.title like '%HCV%'
            AND gpl.manufacturer like '%Illumina%' 
            AND gse.contact like '%Yale%';"))
res.2
```

## Cleanup

```{r}
dbDisconnect(geo_con)
```
